apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: python-deployment
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: python-accelerator
spec:
  source:
    git:
      url: https://github.com/TanzuDK/python-accelerator.git
      ref:
        branch: main
