#@ load("@ytt:data", "data")

apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: #@ data.values.projectName
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: #@ data.values.projectName
  annotations:
    autoscaling.knative.dev/minScale: #@ data.values.minscale
spec:
  source:
    git:
      url: #@ data.values.giturl
      ref:
        branch: #@ data.values.gitbranch
